# Generated by Django 4.2.25 on 2025-10-19 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerType',
            fields=[
                ('player_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('player_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.playertype')),
            ],
        ),
    ]
