# Generated by Django 4.2.25 on 2025-11-09 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('guide_id', models.AutoField(primary_key=True, serialize=False)),
                ('guide', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.guide'),
        ),
    ]
