# Generated by Django 4.2.25 on 2025-11-10 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_guide_user_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='player_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.playertype'),
        ),
    ]
