# Generated by Django 4.2.25 on 2026-05-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_player_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intro_done',
            field=models.BooleanField(default=False),
        ),
    ]
