# Generated by Django 4.2.25 on 2025-10-19 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('career_id', models.AutoField(primary_key=True, serialize=False)),
                ('career_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('insignia_id', models.AutoField(primary_key=True, serialize=False)),
                ('insignia_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('to do', 'To Do'), ('in progress', 'In Progress'), ('done', 'Done')], default='to do', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('progress', models.TextField(blank=True, null=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='exploration.career')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='career',
            name='insignia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='exploration.insignia'),
        ),
    ]
